/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  // docs: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'landing zones intro', 
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: false,
  //     items: [
  //       'landingzones/lz-intro'
  //     ]
  //   },
  //   {
  //     type: 'category',
  //     label: 'module', 
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: false,
  //     items: [
  //       'module/module-intro'
  //     ]
  //   },
  //   {
  //     type: 'category',
  //     label: 'rover', 
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: false,
  //     items: [
  //       'rover/rover-intro'
  //     ]
  //   },
  //   {
  //     type: 'category',
  //     label: 'provider', 
  //     link: {
  //       type: 'generated-index',
  //     },
  //     collapsed: false,
  //     items: [
  //       'provider/provider-intro'
  //     ]
  //   },
  //   {
  //     type: 'category',
  //     label: 'enterprise-scale', 
  //     link: {
  //       type: 'autogenerated',
  //       slug: '/enterprise-scale/landingzones',
  //     },
  //     collapsed: false,
  //     items: [
  //       'enterprise-scale/landingzones/eslz-intro',
  //       'enterprise-scale/landingzones/platform/elsz-level0',
  //       'enterprise-scale/landingzones/platform/org-setup',
  //     ]
  //   },
    
  // ]

};

module.exports = sidebars;
